url: http://ayumi.kagami.moe

markdown: kramdown

permalink: /:title/ #/:title.html

timezone: Asia/Shanghai

author: 明镜止水

name: 曲终人不见江上数峰青

description: 音楽は魔法ではない

highlighter: pygments

safe: true

lsi: false

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: 芦苇荡
